name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "pnpm" # Enable pnpm cache for faster builds

      # Step 3: Install pnpm
      - name: Install pnpm
        run: npm install -g pnpm

      # Step 4: Verify pnpm installation
      - name: Verify pnpm installation
        run: pnpm --version

      # Step 5: Install dependencies
      - name: Install dependencies
        run: pnpm install

      # Step 6: Run linting
      - name: Run linting
        run: pnpm run lint

      # Step 7: Run tests
      - name: Run tests
        run: pnpm test

      # Step 8: Build the app
      - name: Build the app
        run: pnpm run build
